config/routes.rb
Spree::Core::Engine.routes.prepend do
  namespace :admin do
    get '/csv_imports', controller: :csv_imports, action: :index, as: :csv_import_index
    post '/csv_imports/template', controller: :csv_imports, action: :template, as: :csv_import_template, defaults: { format: 'csv' }
    post '/csv_imports/import', controller: :csv_imports, action: :import, as: :csv_import_import, defaults: { format: 'html' }
  end
end

app/models/spree/csv_import.rb
class Spree::CsvImport

  def persisted?
    false
  end

  class << self

    def generate_template(fields)
      ((required_fields + fields).uniq & available_fields).join(',')
    end

    def import(file)
      result = false
      begin
        Spree::Product.transaction do
          spreadsheet = CSV.read(file.path, headers: true)
          result = spreadsheet.size
          spreadsheet.each do |row|
            attrs = row.to_hash.symbolize_keys
            raise if (attrs[:sku].blank? || attrs[:price].blank?)
            attrs[:available_on] = Time.parse(attrs[:available_on]) unless attrs[:available_on].blank?
            Spree::Product.create!(attrs)
          end
        end
        return result
      rescue
        return false
      end
    end

    def required_fields
      %w(name price sku)
    end

    def optional_fields
      %w(description available_on on_hand)
    end

    def available_fields
      required_fields + optional_fields
    end

  end

end

app/controllers/spree/admin/csv_imports_controller.rb
class Spree::Admin::CsvImportsController < Spree::Admin::BaseController
  respond_to :html, :js

  def index
    respond_to do |format|
      format.html { render :layout => !request.xhr? }
      format.js { render :layout => false }
    end
  end

  def template
    respond_to do |format|
      format.csv { send_data Spree::CsvImport.generate_template(params[:import_fields]), filename: 'import_template.csv', type: 'text/csv' }
    end
  end

  def import
    import_result = Spree::CsvImport.import(params[:file])
    respond_to do |format|
      format.html do
        if import_result
          redirect_to admin_products_path, notice: t('csv_import.import_success', :count => import_result)
        else
          redirect_to admin_products_path, flash: { error: t('csv_import.import_error') }
        end
      end
    end
  end

end

app/views/spree/admin/csv_imports/_import_form.html.erb
<%= form_tag(admin_csv_import_import_path, multipart: true, remote: false) do %>
    <fieldset>
      <legend align="center"><%= t('csv_import.import_products') %></legend>
      <div class="field">
        <%= file_field_tag 'file', accept: 'text/csv' %>
      </div>
      <%= submit_tag t('csv_import.import_button') %>
    </fieldset>
<% end %>

app/views/spree/admin/csv_imports/_template_form.html.erb
<%= form_tag(admin_csv_import_template_path(format: "csv"), method: :post) do %>
    <fieldset>
      <legend align="center"><%= t('csv_import.generate_template') %></legend>
      <%- Spree::CsvImport.available_fields.each do |field_name| %>
          <div class="field">
              <%= check_box_tag 'import_fields[]', field_name, true, :id => "import_fields_#{field_name}" %>
              <%= label_tag :sku, t(field_name) %>
          </div>
      <% end %>
      <%= submit_tag t('csv_import.generate_button') %>
    </fieldset>
<% end %>

app/views/spree/admin/csv_imports/index.html.erb
<div id="csv_import_template">
  <%= render partial: 'template_form' %>
</div>
<div id="csv_import_upload">
  <%= render partial: 'import_form' %>
</div>

app/views/spree/admin/csv_imports/index.js.erb
$("#new_product").html('<%= escape_javascript(render :template => "spree/admin/csv_imports/index", :formats => [:html], :handlers => [:erb]) %>');
$("#table-filter").hide();
$("#admin_new_product").parent().show();